[package]
name = "raw-ipa"
version = "0.1.0"
rust-version = "1.57.0"
edition = "2021"

[features]
default = ["debug", "cli"]
cli = ["enable-serde", "structopt", "web-app", "tracing-subscriber"]
debug = ["hex"]
enable-serde = ["serde", "serde_json", "rust-elgamal/enable-serde"]
web-app = ["tokio", "axum", "axum-server", "hyper", "hyper-tls", "tower-http"]
self-signed-certs = ["hyper-tls"]

[dependencies]
aes = "0.8"
axum = { version = "0.5.7", optional = true, features = ["http2"] }
axum-server = { version = "0.4.0", optional = true, features = ["rustls", "rustls-pemfile", "tls-rustls"] }
byteorder = "1"
# rust-elgamal (via curve25519-dalek-ng) only works with digest 0.9, not 0.10
digest = "0.9"

hex = { version = "0.4", optional = true }
# rust-elgamal (via curve25519-dalek-ng) only works with digest 0.9, so pin this
hkdf = "0.11"
hyper = { version = "0.14.19", optional = true, features = ["client", "h2"] }
hyper-tls = { version = "0.5.0", optional = true }
log = "0.4"
# This is stupid, but we have packages that want this old interface
# those have to use the same RNG as packages that want the new interface.
old_rand_core = { package = "rand_core", version = "0.5", default-features = false }
rand = "0.8"
rand_core = "0.6"
redis = "0.21.5"
rust-elgamal = "0.4"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
# rust-elgamal (via curve25519-dalek-ng) only works with digest 0.9, so pin this
sha2 = "0.9"
structopt = { version = "0.3", optional = true }
thiserror = "1.0"
tokio = { version = "1.19.2", optional = true, features = ["rt", "rt-multi-thread", "macros"] }
tower-http = { version = "0.3.4", optional = true, features = ["trace"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", optional = true }
x25519-dalek = "1"

[dev-dependencies]
hex = "0.4"
lazy_static = "1.4.0"
proptest = "1.0.0"

[lib]
name = "raw_ipa"
path = "src/lib.rs"

[[bin]]
name = "ua"
required-features = ["cli"]

[[bin]]
name = "helper"
required-features = ["cli"]
