[package]
name = "raw-ipa-esrc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-elgamal = "0.4.0"
bls12_381 = "0.6.0"
rand = "0.8.5"